Repository newfold-labs/wp-module-onboarding-data, pull requests merged in 2024-01, with the labels that each got.

#25 Add the onboarding status option and a coming soon helper
  composer.json
  composer.lock
  includes/Data.php
  includes/Options.php
  includes/Services/FlowService.php
Labels: Ready to merge

#28 Add service method for the Customize sidebar data
  includes/Services/SiteGenService.php
  includes/Themes/Colors.php
  includes/Themes/Fonts.php
Labels: In Progress

#24 Api integration preview home page
  includes/Options.php
  includes/Services/SiteGenService.php
Labels: Code Review

#20 Adding data for simple customer promt screen
  includes/Flows/Flows.php
  includes/SiteGen.php
Labels: Code Review

#30 Activate WooCommerce by Preview step
  includes/Plugins.php
Labels: Code Review

#31 Add homepages to Wonder Blocks templates
  composer.json
  composer.lock
  includes/Services/SiteGenService.php
Labels: Code Review

#29 AI Sitegen Capability Check
  includes/Brands.php
  includes/Config.php
Labels: Code Review

#33 Sitegen: Code Refactor and Post-Integration Fixes
  includes/Options.php
  includes/Services/FlowService.php
  includes/Services/SiteGenService.php
Labels: Code Review

#35 Use header and footer patterns for template parts
  includes/Flows/Flows.php
  includes/Mustache/Mustache.php
  includes/Services/SiteGenService.php
  includes/Services/SitePagesService.php
  includes/Services/ThemeGeneratorService.php
Labels: Code Review
