Repository newfold-labs/wp-module-onboarding-data, pull requests merged in 2024-02, with the labels that each got.

#38 Use a static image for sitegen generated themes
  includes/Services/SiteGenService.php
  includes/Services/ThemeGeneratorService.php
  includes/assets/images/screenshot.png
Labels: Code Review

#37 Sitegen flow related data
  composer.json
  composer.lock
  includes/Brands.php
  includes/Config.php
  includes/Data.php
  includes/Flows/Flows.php
  includes/Mustache/Mustache.php
  includes/Mustache/Templates/themeStylesheet.mustache
  includes/Options.php
  includes/Plugins.php
  includes/Services/FlowService.php
  includes/Services/SiteGenService.php
  includes/Services/SitePagesService.php
  includes/Services/ThemeGeneratorService.php
  includes/SiteGen.php
  includes/Themes.php
  includes/Themes/Colors.php
  includes/Themes/Fonts.php
  includes/assets/images/screenshot.png
Labels: QA

#39 Bump Onboarding Data to 1.0.0
  composer.json
  composer.lock
  includes/Services/SiteGenService.php
Labels: Code Review

#40 Bump AI and handle generatedImages in homepage response
  composer.json
  composer.lock
  includes/Services/SiteGenService.php
Labels: Code Review

#41 updated flow
  includes/Flows/Flows.php
Labels: QA

#42 Block Render and Screenshots
  includes/Services/BlockRenderService.php
  includes/Services/SiteGenService.php
  includes/Services/ThemeGeneratorService.php
Labels: Code Review

#43 Fix Regex for homepages
  includes/Services/SiteGenService.php
Labels: In Progress

#51 Sitegen: Set Site Classification Once Generated
  includes/Services/SiteGenService.php
Labels: Code Review

#47 Replace menu items in previews with those from the sitemap
  includes/Patterns.php
  includes/Services/SiteGenService.php
Labels: Code Review

#48 Add Site Title and Tagline
  includes/Services/SiteGenService.php
Labels: Code Review

#49 Sitegen: Trash sample page upon clicking Save & Continue
  composer.json
  composer.lock
  includes/Services/SiteGenService.php
  includes/Services/SitePagesService.php
Labels: Code Review

#50 Sitegen: Wonder Blocks Fixes and Prioritization
  includes/Services/SiteGenService.php
Labels: Code Review

#45 Setting page title from sitemap options
  includes/Services/SiteGenService.php
Labels: Code Review

#54 Sitegen: Organize navigation menus
  includes/Services/SiteGenService.php
Labels: Code Review

#56 Sitegen: Fix Site Logo Data
  includes/Flows/Flows.php
  includes/Services/FlowService.php
Labels: Ready to merge

#55 Sitegen: Analytics
  includes/Events.php
Labels: Ready to merge

#53 increment sitegen meta status total counts
  includes/Flows/Flows.php
Labels: Code Review

#44 Update Flows.php
  composer.json
  composer.lock
  includes/Flows/Flows.php
Labels: enhancement, Code Review
