Repository newfold-labs/wp-module-onboarding-data, pull requests merged in 2024-03, with the labels that each got.

#60 Install Plugins Extended
  includes/Plugins.php
Labels: Ready to merge

#61 Fix unnecessary sitemap AI calls
  includes/Patterns.php
Labels: Ready to merge

#58 minor fix for warning
  includes/Flows/Flows.php
  includes/Services/FlowService.php
  includes/Services/SiteGenService.php
  includes/Services/ThemeGeneratorService.php
Labels: QA

#64 Sitegen: Add Event for Error State
  includes/Events.php
Labels: QA

#65 Fix `Priorities`
  includes/Plugins.php
Labels: Code Review
