Repository newfold-labs/wp-module-onboarding-data, pull requests merged in 2024-05, with the labels that each got.

#78 Apply Fork A/B Test Winner
  includes/Events.php
  includes/Flows/Flows.php
Labels: Ready to merge

#71 Add `isFreshInstallation` to data
  composer.json
  composer.lock
  includes/Data.php
  includes/Flows/Flows.php
Labels: QA

#79 Use Major Versions for Patterns
  composer.json
  composer.lock
Labels: Code Review

#80 Change the visibility of the `is_fresh_installation` function to public
  includes/Data.php
Labels: Ready to merge

#75 added canMigrateSite flag to brands
  includes/Brands.php
  includes/Config.php
Labels: QA

#83 Limit AI Retries
  includes/Flows/Flows.php
  includes/Services/SiteGenService.php
Labels: Ready to merge

#86 Generate names for options
  includes/Services/SiteGenService.php
  includes/Services/SitePagesService.php
Labels: Ready to merge

#90 Change Activation for Yith Plugins
  includes/Plugins.php
Labels: Ready to merge

#91 Update Onboarding Data to 1.1.10
  composer.lock
Labels: Ready to merge
